### ISSUE TITLE
env promblem

### ISSUE THREAD

**Issue by jinyl777** [dvl-tum/mot_neural_solver#10]
Hi i got two issues ，could you  help me 
1.Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ld_impl_linux-64==2.34=h53a641e_4

2.pip install -e tracking_wo_bnw
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:

**Comment by elgehelge** [comment]
> Hi i got two issues ，could you help me
> 1.Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
> 
> * ld_impl_linux-64==2.34=h53a641e_4
> 

Look at https://github.com/dvl-tum/mot_neural_solver/issues/9

> 2.pip install -e tracking_wo_bnw
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:

It could be either of the following:
1. You are not in the repository root directory.
2. You didn't manage to clone the repository recursively, which means that you don't have a directory called "tracking_wo_bnw"
3. You somehow deleted the setup.py file from that directory.

**Comment by jinyl777** [comment]
1. I have tracking_wo_bnw directory , 
and don not deletd zhe setup ,
and in the mot_neural_solver directory ,there have  tracking_wo_bnw directory , 
so i don not solver zhe problem

i  use conda list | grep ld_impl_linux-64 this but have nothing output

**Comment by gbraso** [comment]
Hi @jinyl777, I'm not sure I can help much with the environment issue. Have you tried simply deleting this line from environment.yaml? Please, as @elgehelge mentioned, look at #9 and post any questions regarding this there, to avoid having duplicated issues.

As for your problem installing tracktor: are you sure you have the 'tracking_wo_bnw' directory and it's not empty? (does tracking_wo_bnw/setup.py exist?)

**Comment by jinyl777** [comment]
sorry I do not check it .I solver my problem ,thank you very much.

**Comment by Reeshark** [comment]
Hi @jinyl777. I have same problem that when I type the "conda list | grep ld_impl_linux-64", but it doesn't have any output, how did you solve this problem?

**Comment by jinyl777** [comment]
So long time ago I solved the promble ，I just rember comment certain line in requirement.txt
