### ISSUE TITLE
How to train the model on Custom dataset?

### ISSUE THREAD

**Issue by yutliu** [dvl-tum/mot_neural_solver#11]
May I know the procedure to train the model on a custom dataset?
Thanking you in anticipation!

**Comment by gbraso** [comment]
Hi,

You first have to store your data in the MOTChallenge's format (please see https://motchallenge.net/). After that, you need to do a few code modifications:
- Adapt Tracktor's code to be able to process your new sequences. You need to go to the tracking_wo_bnw directory and modify files 'src/tracktor/datasets/factory.py' (to include a dataset consisting of your own video sequences), 'src/tracktor/datasets/mot_sequence.py' (to create a 'Sequence' class for your videos, you can probably reuse most code from 'MOT17Sequence') and src/tracktor/datasets/mot_wrapper.py.
- Adapt the mot_neural_solver code to be able to process your new sequences. Please check out 'src/mot_neural_solver/data/seq_processing/seq_processor.py'. There you'll find an explanation of what you need to do. Also, make sure to add some split in 'src/mot_neural_solver/data/splits.py' that contains your new sequences, and include under 'data_splits'  in the configuration file 'configs/tracking_cfg.yaml'.
- After that, you should be able to proceed as with any MOTChallenge sequence. So you should first run the preprocessing and train/evaluate models as explained in the README.

I hope this helps!!

**Comment by yutliu** [comment]
Thank you for your detailed answers! I will follow these steps.

**Comment by gbraso** [comment]
You're welcome! :)  Can I close this issue?
