### ISSUE TITLE
MOV_CAMERA_DICT meaning

### ISSUE THREAD

**Issue by hyperparameters** [dvl-tum/mot_neural_solver#15]
Im trying to implement this on custom dataset
what does mapping in `MOV_CAMERA_DICT` dict means 
in `data/seq_processing/****loader.py`

**Comment by tobiasolof** [comment]
I believe it's a boolean per sequence indicating if the corresponding video was recorded with a moving or static camera.

**Comment by hyperparameters** [comment]
@tobiasolof i was also assuming the same, thanx

**Comment by Ilikeyou3000** [comment]
Moving camera dataset will be sampled in 9fs , while static is sampled 6fps。 which probably means moving camera dataset call for more continuity. you will see  this in track_cfg.yaml, using ctrl+F.

**Comment by hyperparameters** [comment]
@Ilikeyou3000 Thanx for the details
