### ISSUE TITLE
how to use  multiple GPUs to train and test？

### ISSUE THREAD

**Issue by ly59782** [dvl-tum/mot_neural_solver#16]
There is too many detections in a single frame in my dataset, so when i test, it would raise CUDA out of memery runtime error. May I ask what should I modify to use multiple gpus???

**Comment by gbraso** [comment]
Hi! Adapting the code for using several GPUs for testing would not straightforward. Could you provide more details on where you're getting CUDA OOM errors in the code?

**Comment by ly59782** [comment]
There is about 400 detections in a single frame in the most compex scene, so when testing, it seems that the constructed MOTgraph is too big to put in a single GPU. We tried to reduce the parameter "frames_per_graph", the CUDA OOM error would disappear. However it would make the final MOTA and other metrics get worse. I wonder whether it is possible to use multiple GPUs to solve this problem. Many thanks.

**Comment by gbraso** [comment]
Hi, can you please show me your error message? 
Most likely, this error is happening due to some 'expensive operations' (pairwise distance computations) that take place in src/mot_neural_solver/data/mot_graph.py. These operations are done on the GPU for speed but can be probably performed on the CPU or batched with very small code changes, and no significant speed loss (whereas using multiple GPUs would actually require significant changes). 
If you show me a screenshot of your error messages, I'll be able to give you a more specific answer!

**Comment by ly59782** [comment]
![QQ图片20200714165001](https://user-images.githubusercontent.com/39304054/87405473-15663a00-c5f2-11ea-963b-0b51bc313024.png)

**Comment by gbraso** [comment]
Thanks. I think that adding self.full_graph.graph_obj.cpu() in line 162 in src/mot_neural_solver/tracker/mpn_tracker.py  (right before calling 'to_undirected_graph') should solve the issue, and speed should be approx the same.

Another question: what is the length of your video sequences? (i.e. how many frames do you have and total number of object detections for the whole sequence?

**Comment by ly59782** [comment]
There are 234 frames in one sequence and about 234*450 detections in the whole sequence

**Comment by ly59782** [comment]
I added the code self.full_graph.graph_obj.cpu() in line 162 , and the CUDA OOM error disappear, but it cost much more time (40 mintues passed and the test is still running) to test half sequence(if i directly test an entire sequence, it would use too much CPU memory and the process would be killed).

**Comment by MrMorning** [comment]
> Hi, can you please show me your error message?
> Most likely, this error is happening due to some 'expensive operations' (pairwise distance computations) that take place in src/mot_neural_solver/data/mot_graph.py. These operations are done on the GPU for speed but can be probably performed on the CPU or batched with very small code changes, and no significant speed loss (whereas using multiple GPUs would actually require significant changes).
> If you show me a screenshot of your error messages, I'll be able to give you a more specific answer!

Hi, noticed that you mentioned we can make small code changes to let pairwise_distance to be computed in batch or cpu without speed loss. Any specified suggestion on how to implement this? Thx! :-)  (Currently confused about OOM error caused by pairwise_distance computing when tracking...)
