### ISSUE TITLE
I confrot with a devastating problem on frcnn_epoch_27.pt.tar

### ISSUE THREAD

**Issue by LOVEYRR** [dvl-tum/mot_neural_solver#19]
When I get access to the modle：frcnn_epoch_27.pt.tar ，just like this：https://vision.in.tum.de/webshare/u/brasoand/mot_neural_solver/frcnn_epoch_27.pt.tar

I can totally get the right bag（frcnn_epoch_27.pt.tar）！
**but I cannot decompress it because it shows that the file is corrupted!**.

so I wonder if you could send me a frcnn_epoch_27.pt.tar **that can be used**？or just update it on this repository.

thank you very much！

**Comment by gbraso** [comment]
Hi. Sorry for my late reply. I reuploaded the file. Can you check again? If it still doesn't work, I can send you the file e.g. via email!

**Comment by gbraso** [comment]
I've just realized that the issue was that you shouldn't be decompressing the file in the first place but just loading it with PyTorch in the same format that you downloaded it. The file I provide is not corrupted, please see #20.
