### ISSUE TITLE
MOT20 detections

### ISSUE THREAD

**Issue by tiberium24** [dvl-tum/mot_neural_solver#20]
Hello, 

Would it be possible to provide detections processed with Tracktor for MOT 20?

**Comment by gbraso** [comment]
Hi! Sorry for my super late reply! I've just updated the repository, and we now provide overall support for MOT20: we have published preprocessed detections by tracktor (see Setup in the README), code for fine-tuning tracktor, and the checkpoints corresponding to an MPN trained on MOT20, and tracktor fine-tuned on it! I hope It can still be of use to you!

**Comment by RHenschel** [comment]
Thanks for uploading the files! It seems that the model tar file is somehow corrupted. I cannot unpack it. 

Can you fix this?

**Comment by gbraso** [comment]
@RHenschel Which model, Tracktor or the MPN? In principle, you should not need to unpack it directly, just calling torch.load on the file you download directly should work. Does it not work?

**Comment by RHenschel** [comment]
@gbraso I meant the Tracktor model. I thought I had to unpack the tar file first. The model works, thanks alot :)
