### ISSUE TITLE
train and val on mot16 

### ISSUE THREAD

**Issue by iamZe** [dvl-tum/mot_neural_solver#24]
Hello sir, nice work!

may I know what I need to do if I need to do training on mot16? Thanks.

**Comment by Newdxz** [comment]
hello，Did you run this program correctly，I encountered some problems in the evaluate, can I ask you something, Thanks

**Comment by gbraso** [comment]
Dear @iamZe,

Thanks for your kind comment! MOT16 contains the same sequences as MOT17, but MOT17 has improved annotations. As for the public detections, MOT17's DPM detections are exactly the same ones given as MOT16 public detections. Hence, using MOT17 is preferable to using MOT16. In summary, for 

If you still want to train on MOT16, you'd have to download the annotations from this [link](https://motchallenge.net/data/MOT16Labels.zip), and extract them in `DATA_PATH`. Then you could essentially reuse the code in `src/mot_neural_solver/data/seq_processing/MOTCha_loader.py` used for the MOT17 dataset to load MOT16 annotations / detection files. Hope this was clear. 

If you need further help please let me know!

**Comment by gbraso** [comment]
Hi @Newdxz . What problem did you encounter? there was a typo in the configuration file path in `scripts/evaluate.py`. It was written `configs/tracking_config.yaml` instead of `configs/tracking_cfg.yaml`. But I have now fixed it. If you were facing a different problem, then please open a separate issue for it. Thanks!!

**Comment by iamZe** [comment]
@Newdxz sure, lets figure out problems together

**Comment by gbraso** [comment]
Hi!
If I'm not mistaken, @Newdxz problems were already addressed in #22. Am I right? 
@iamZe do you still need help with MOT16, or can I close this issue?

**Comment by iamZe** [comment]
yes please @gbraso
