### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by szh91** [dvl-tum/mot_neural_solver#25]
Solving environment: failed
ResolvePackageNotFound:
  - ld_impl_linux-64==2.34=h53a641e_4
  - libgfortran-ng==7.5.0=hdf63c60_6

**Comment by gbraso** [comment]
Please, check out #9. If it doesn't work, you can try just deleting these two lines from the `environment.yaml` file.

**Comment by szh91** [comment]
thank you! By the way, is there any requirement for the cuda version? My cuda version is 9.0

**Comment by gbraso** [comment]
The code was tested with 10.1, but I initially developed with 9.2. I think 9.0 should work, let me know if it doesn't!

**Comment by szh91** [comment]
yes, no error in the subsequent configuration environment

**Comment by gbraso** [comment]
Great, can I close this issue?

**Comment by szh91** [comment]
yes, thank you again

**Comment by gbraso** [comment]
you're welcome :)
