### ISSUE TITLE
Problems regarding to evaluate on MOT test set

### ISSUE THREAD

**Issue by gaojiaxi** [dvl-tum/mot_neural_solver#26]
Hi,

Thank you for sharing this nice work.

I tried to run the evaluation part, however I was not able to do so as the gt.txt files are missing for the test set.

FileNotFoundError: [Errno 2] No such file or directory: '/home/gaojiaxi/mot_neural_solver/data/MOT_eval_gt/TUD-Crossing/gt/gt.txt'

I tried to search on the repository and also on the MOT website but I coundn't find the gt file for test set as well.

Can you help in this case?

Thanks

**Comment by gbraso** [comment]
Hi,

Thanks for your comment :)

The sequence 'TUD-Crossing' belongs to the MOT15 Challenge test set. You cannot download ground truth annotations for any test sequence for any of the MOTChallenge datasets. Evaluation of test sequences is performed in the MOTChallenge server: you have to submit your results to the website, and you will get back your performance metrics.
