### ISSUE TITLE
a Question

### ISSUE THREAD

**Issue by jiaweihe1996** [dvl-tum/mot_neural_solver#7]
Hi. Thanks for your code. I have a question about it. I think there is a little difference between your code and the paper. In the code below, when you calculate ![CodeCogsEqn](https://user-images.githubusercontent.com/27729041/84763497-e06cc480-affe-11ea-9dbf-29b90cd54d2e.gif), I think `x[flow_out_col]` means node feature j (![2](https://user-images.githubusercontent.com/27729041/84763658-27f35080-afff-11ea-9864-083c091b30b9.gif)) instead of node feature i (![3](https://user-images.githubusercontent.com/27729041/84763613-114cf980-afff-11ea-87cf-1b27aaf4d458.gif)) in equation 6 in your paper. Is that right? 

https://github.com/dvl-tum/mot_neural_solver/blob/e79b2ded0d0d5f857bcad98de6c4ff9e505ea867/src/mot_neural_solver/models/mpn.py#L86
https://github.com/dvl-tum/mot_neural_solver/blob/e79b2ded0d0d5f857bcad98de6c4ff9e505ea867/src/mot_neural_solver/models/mpn.py#L92

**Comment by gbraso** [comment]
Hi! You're right, we had not realized this, so thank you for noticing and letting us know. We'll correct these formulas in the next update of our arXiv paper.

Thanks again for pointing this out!

**Comment by gbraso** [comment]
Can I close this issue?

**Comment by jiaweihe1996** [comment]
Yes, I have closed it. Thank you vrey much.
