### ISSUE TITLE
can't find config.ymal

### ISSUE THREAD

**Issue by Ilikeyou3000** [dvl-tum/mot_neural_solver#8]
Hi，I am trying to reproduce your results!
I encount a problem. In code `cross_validation.py` , there is a yaml :
    `ex.add_config('/usr/stud/brasoand/mpn_tracking/configs/config.yaml')`. 

As  no keyword `run_id`  appears in any yaml of `configs` folder, I expect there is another config file `config.yaml` to be uploaded. Is that right?

**Comment by Ilikeyou3000** [comment]
haha, It must be refer to tracking_cfg.yaml

**Comment by gbraso** [comment]
Thanks for bringing that up! 
You're right, the actual file was configs/tracking_cfg.yaml. I just updated the code :)
