### ISSUE TITLE
Error while creating environment

### ISSUE THREAD

**Issue by nihuo76** [dvl-tum/mot_neural_solver#9]
Hi, I was trying to follow the tutorial step by step. But I always get this error. 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_4

May I ask if you have any idea on this? Many thanks

**Comment by nihuo76** [comment]
I googled and this seems to be a problem of anacodna. Can you provide the version number of anaconda and conda you using?

**Comment by Ilikeyou3000** [comment]
`conda list | grep ld_impl_linux-64`  
and it gives out `ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge`
substitute corespond item in environment.yaml. 
It works anyway

**Comment by gbraso** [comment]
Hi @nihuo76, did @Ilikeyou3000's help fix your problem?

**Comment by nihuo76** [comment]
@gbraso I got around by installing the package needed by hand in command line window one by one.

**Comment by gbraso** [comment]
I'm glad that you could make it work, @nihuo76. Can I close this issue, then?

**Comment by matteoTaiana** [comment]
Hi @gbraso and everyone,
I ran into this problem on Ubuntu 20.04.
The suggestion by @Ilikeyou3000 solved it for me.

**Comment by fangxueshan** [comment]
> Hi, I was trying to follow the tutorial step by step. But I always get this error.
> 
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
> 
> * ld_impl_linux-64==2.34=h53a641e_4
> 
> May I ask if you have any idea on this? Many thanks
Hello.I want to ask about the hardware configuration of this experiment

**Comment by Newdxz** [comment]
I download this tar and install in local

**Comment by nihuo76** [comment]
> I'm glad that you could make it work, @nihuo76. Can I close this issue, then?

Sure, please close the issue.

**Comment by wzwb** [comment]
> `conda list | grep ld_impl_linux-64` and it gives out `ld_impl_linux-64 2.33.1 h53a641e_7 conda-forge` substitute corespond item in environment.yaml. It works anyway

Thank you！
